services:
  pg:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRE_USER=docker
      - POSTGRE_PASSWORD=docker
      - POSTGRE_DATABASE=brevly
    volumes:
      - ./docker:/docker-entrypoint-initdb.d